language: node_js
node_js:
- 7.9.0
before_install:
- openssl aes-256-cbc -K $encrypted_127ff09fbefd_key -iv $encrypted_127ff09fbefd_iv
  -in id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh -f

- chmod 600 ~/.ssh/id_rsa

# 配置 ssh

- eval $(ssh-agent)

- ssh-add ~/.ssh/id_rsa

- cp .travis/ssh_config ~/.ssh/config
after_script:

- scp -o StrictHostKeyChecking=no app.js evan@192.168.1.103:/home/www/nodetest